swagger: '2.0'
info:
  title: Data Item API
  version: "1.0.0"
host: data.calculator.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /data-items/{type}:
    get:
      summary: Get annual results based on data-item type
      parameters:
        - name: type
          in: path
          description: The calculation type (alpha, beta, gamma)
          required: true
          type: string
        - name: company_id
          in: query
          description: Company numeric identifier
          required: true
          type: number
          format: integer
      responses:
        200:
          description: An array of data items
          schema:
            type: array
            items:
              $ref: '#/definitions/DataItem'
 
definitions:
  DataItem:
    type: object
    properties:
      year:
        type: number
        format: integer
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      value:
        type: number
        format: double
        description: Description of product.
 

